# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.21.6'

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a.size

10

In [ ]:
a.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.sum)

 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>, where=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer 

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a=np.arange(1,11)
print(a)
a[4]=1
a

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  1,  6,  7,  8,  9, 10])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
b=np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random((3,3,3))

array([[[0.00106897, 0.9430137 , 0.56784558],
        [0.36844599, 0.96642496, 0.92839783],
        [0.42798485, 0.32696147, 0.56080042]],

       [[0.01234825, 0.2266877 , 0.63372909],
        [0.46217009, 0.06582436, 0.62684675],
        [0.63035927, 0.72527802, 0.87671369]],

       [[0.63278269, 0.13783752, 0.3769062 ],
        [0.46035187, 0.15475854, 0.98169897],
        [0.6498679 , 0.27186911, 0.55576191]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
c=np.random.random((10,10))
print(c)
print(c.min(),c.max())

[[0.46756686 0.66922103 0.03743315 0.68624746 0.8513983  0.16782915
  0.03960741 0.95351848 0.63755784 0.61838259]
 [0.38013813 0.96192333 0.48526201 0.04811475 0.94766826 0.50511241
  0.45361273 0.8856638  0.32622756 0.78936819]
 [0.2442413  0.21155326 0.82261566 0.13030531 0.95023599 0.6547782
  0.64672754 0.25098792 0.824963   0.22232054]
 [0.99053833 0.5675307  0.84436715 0.83265655 0.1495064  0.0537622
  0.54990355 0.45033599 0.13854629 0.173534  ]
 [0.99315405 0.16024246 0.41326364 0.34389242 0.376825   0.71486757
  0.02312614 0.83537303 0.07127631 0.25575883]
 [0.93071898 0.03989192 0.14558456 0.7877559  0.9237793  0.01015065
  0.56492626 0.90920581 0.40183024 0.51618998]
 [0.47974771 0.70014599 0.09470067 0.65187642 0.04215869 0.64493142
  0.38984383 0.08338324 0.46392027 0.38935763]
 [0.09266139 0.95531976 0.10606846 0.72475984 0.1422654  0.58673822
  0.12788271 0.45671174 0.8912714  0.74577692]
 [0.18857996 0.8373058  0.62158209 0.71805052 0.36091639 0.68672497
  0.16865528 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
d=np.random.random(30)
d.mean()

0.4400579006296476

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
e=np.ones((5,5))
e[1:-1,1:-1]=0
e

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
print(e)
np.pad(e,pad_width=3,mode="constant",constant_values=0)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
H=np.random.random((5,5))
H = (H - H.min())/(H.max() - H.min())
H

array([[0.17416848, 0.65619   , 0.45708051, 0.72762148, 0.86955955],
       [0.49171533, 0.32498264, 0.33625486, 0.        , 0.00940251],
       [0.08645911, 0.81246472, 0.79942627, 0.15788185, 0.71657177],
       [1.        , 0.50811794, 0.22334273, 0.18074534, 0.22428667],
       [0.7083251 , 0.47666429, 0.18131692, 0.27152661, 0.46906632]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([('r',np.uint8),('g',np.uint8),('b',np.uint8),('a',np.uint8)])
color = np.array((1,2,3,4),dtype = RGBA)
print(color['a'])
type(color)

4


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x=np.random.random((5,3))
y=np.random.random((3,2))
np.dot(x,y)

array([[1.08777839, 1.30542196],
       [1.13923657, 1.02223926],
       [1.07572987, 1.04555578],
       [1.44828436, 1.56474045],
       [0.35470869, 0.67648373]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
h=np.arange(1,11)
print(h)
h[(3<h)&(h<8)]*=-1
h

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z=arange(1,10)
print(z**z)
print(2<<z<<2)
print(z<-z)
print(1j*z)
print(z/1/1)
#print(z<z>z)

[        1         4        27       256      3125     46656    823543
  16777216 387420489]
[  16   32   64  128  256  512 1024 2048 4096]
[False False False False False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0)/np.array(0)
np.array(0)//np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
i=np.random.uniform(-9,4,5)
print(i)
np.copysign(i,+2)
np.ceil(i)
np.abs(i)

[ 2.92714184 -2.49655607  3.83984047  3.99422222 -3.4923134 ]


array([2.92714184, 2.49655607, 3.83984047, 3.99422222, 3.4923134 ])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
g=np.arange(1,12)
h=np.arange(5,17)
np.intersect1d(g,h)

array([ 5,  6,  7,  8,  9, 10, 11])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all="ignore")

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2022-07-27
Today:  2022-07-28
Tomorrow:  2022-07-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
i=np.linspace(1,10,10)
print(i)
print(i-i%2)
print(np.floor(i))
print(np.ceil(i))
print(np.trunc(i))
print(i.astype(complex))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.  2.  2.  4.  4.  6.  6.  8.  8. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
A = np.zeros((5,5))
A += np.arange(5)
A

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
  for i in range(0,10):
        yield i
np.fromiter(generate(),dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
i=np.random.random(10)
i.sort()
print(i)

[0.02704185 0.05274603 0.17463472 0.20675739 0.29490085 0.38558317
 0.44854609 0.52799124 0.76260427 0.77600986]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
a= np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x= np.zeros(10)
x.flags.writeable = False
#x[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]
R=np.sqrt(x**2 + y**2)
D=np.arctan2(y,x)
print(R)
print(D)

[0.77357305 0.93183904 0.59595373 1.00413363 1.08994881 0.45819666
 1.0087766  0.81829021 0.57071727 0.66724133]
[0.28652598 1.04627369 1.15176322 0.63814062 0.95580334 1.08900547
 0.53308939 0.94462416 0.32977063 1.30306628]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
a=np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.68461197 0.74779775 0.25771045 0.32682668 0.75751349 0.00634107
 0.60175339 0.24597351 0.         0.09414218]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
A = np.ones((5,5), [('x',int),('y',int)])
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(A)

[[(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 1) (0, 1) (0, 1) (0, 1) (1, 1)]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(1,5).reshape(2,2)
Y = np.arange(5,9).reshape(2,2)
print(X)
print(Y)
A = (1/(np.subtract.outer(X,Y)))
A

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[[[-0.25      , -0.2       ],
         [-0.16666667, -0.14285714]],

        [[-0.33333333, -0.25      ],
         [-0.2       , -0.16666667]]],


       [[[-0.5       , -0.33333333],
         [-0.25      , -0.2       ]],

        [[-1.        , -0.5       ],
         [-0.33333333, -0.25      ]]]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
a=np.zeros((20,20))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a=np.arange(100)
b=np.random.uniform(0,100)
index=(np.abs(a-b)).argmin()
print(a[index])

40


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
x= np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
D

array([[0.        , 0.21997655, 0.19619592, 0.03473495, 0.67769529,
        0.29634713, 0.36803737, 0.43653885, 0.55873882, 0.20051864],
       [0.21997655, 0.        , 0.1131779 , 0.18918861, 0.46902131,
        0.07960419, 0.44586196, 0.31233961, 0.59235952, 0.09882735],
       [0.19619592, 0.1131779 , 0.        , 0.17926568, 0.4916399 ,
        0.17932311, 0.3340111 , 0.42467111, 0.48041144, 0.1910453 ],
       [0.03473495, 0.18918861, 0.17926568, 0.        , 0.65172984,
        0.26406001, 0.38692756, 0.40348458, 0.57328321, 0.16579398],
       [0.67769529, 0.46902131, 0.4916399 , 0.65172984, 0.        ,
        0.41268648, 0.71320873, 0.57855037, 0.73745784, 0.54516666],
       [0.29634713, 0.07960419, 0.17932311, 0.26406001, 0.41268648,
        0.        , 0.51227356, 0.27064422, 0.64504759, 0.1324892 ],
       [0.36803737, 0.44586196, 0.3340111 , 0.38692756, 0.71320873,
        0.51227356, 0.        , 0.75125304, 0.19984821, 0.50379719],
       [0.43653885, 0.31233961, 0.4246711

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a=np.arange(10, dtype=np.float32)
b=a.astype(np.int32,copy=False)
print(a)
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11""")
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n=5
p=5
z=np.zeros((n,n))
np.put(z,np.random.choice(arange(n*n), p, replace=False),1)
print(z)

[[0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [67]:
x=np.random.rand(5, 5)
y=x-x.mean(axis = 1,keepdims = True)
print(y)
y=x.mean(axis = 1).reshape(-1,1)

[[ 0.03159449 -0.01893725 -0.19865363 -0.07084342  0.25683981]
 [ 0.09695348  0.26283051 -0.38071819  0.17561521 -0.15468101]
 [ 0.19376475 -0.20371558  0.16332761 -0.0908068  -0.06256998]
 [-0.0888943  -0.03553804 -0.35575126  0.17504549  0.30513811]
 [ 0.44026284  0.22690832 -0.1492186  -0.28060225 -0.23735031]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [68]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[2 2 2]
 [7 7 8]
 [7 3 8]]
[[2 2 2]
 [7 3 8]
 [7 7 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [69]:
z=np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [70]:
Z = np.random.uniform(0,1,10)
z = 0.5
nv = Z.flat[np.abs(Z - z).argmin()]
print(nv)

0.5458355690779755


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [2]:
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None])
for x,y,z in it:
  z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [79]:
class Array(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z= Array(np.arange(5), "range_is_5")
print(Z.name)

range_is_5


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [80]:
x= np.ones(10)
y= np.random.randint(0,len(x),20)
x+= np.bincount(y, minlength=len(x))
print(x)

np.add.at(x, y, 1)
print(x)

[1. 4. 5. 4. 3. 1. 2. 2. 4. 4.]
[1. 7. 9. 7. 5. 1. 3. 3. 7. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [3]:
a=[3,6,9,12,15,18]
b=[2,4,6,8,9,10]
np.bincount(a,b)

array([ 0.,  0.,  0.,  2.,  0.,  0.,  4.,  0.,  0.,  6.,  0.,  0.,  8.,
        0.,  0.,  9.,  0.,  0., 10.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [7]:
w,h=16,16
I=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F=I[...,0]*(256*256)+I[...,1]*256+I[...,2]
N=len(np.unique(F))
print(N)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [8]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[40 54 62 43]
 [42 46 50 78]
 [68 48 59 46]]
[[40 54 62 43]
 [42 46 50 78]
 [68 48 59 46]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [9]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.52839331 0.4553279  0.51265497 0.5015736  0.47020262 0.57196386
 0.64602961 0.43077999 0.45194064 0.54359512]
0    0.528393
1    0.455328
2    0.512655
3    0.501574
4    0.470203
5    0.571964
6    0.646030
7    0.430780
8    0.451941
9    0.543595
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [12]:
A = np.random.uniform(0,1,(2,2))
B = np.random.uniform(0,1,(2,2))
np.diag(np.dot(A, B))

array([0.60530457, 0.50126978])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [13]:
V=np.array([1,2,3,4,5])
Zn=3
X=np.zeros(len(V)+(len(V)-1)*Zn)
X[::Zn+1]=V
X

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [14]:
A=2*np.ones((5,5,3))
B=2*np.ones((5,5))
print(A*B[:,:,None])

[[[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [16]:
A=np.arange(16).reshape(4,4)
print(A)
A[[0,1]]=A[[1,0]]
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [2]:
faces=np.random.randint(0,100,(10,3))
f=np.roll(faces.repeat(2,axis=1),-1,axis=1)
f=f.reshape(len(f)*3,2)
F=np.sort(f,axis=1)
g=f.view(dtype=[('p0',f.dtype),('p1',f.dtype)] )
g=np.unique(g)
print(g)

[( 0, 24) ( 1, 67) ( 4, 86) ( 6, 53) ( 8, 84) (14,  6) (14,  8) (23, 76)
 (24, 87) (27, 31) (31, 63) (34,  1) (37,  4) (50, 53) (50, 73) (53, 14)
 (53, 54) (54, 50) (59, 85) (63, 23) (63, 27) (64, 59) (67, 34) (73, 91)
 (76, 63) (84, 14) (85, 64) (86, 37) (87,  0) (91, 50)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [4]:
a=np.bincount([1,3,4,5,7,11,2,3,4])
b=np.repeat(np.arange(len(a)),a)
print(b)

[ 1  2  3  3  4  4  5  7 11]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [7]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(25)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [8]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [9]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.87534951,  0.82319276,  0.88615923, -0.92168234, -0.22730681,
       -0.3512736 , -0.48772155,  0.49945217,  0.91284217,  0.42299148,
       -0.35056945,  0.40399673,  0.97539763, -0.04042929,  0.99900988,
        0.1798744 , -0.53189066, -0.76599658, -0.13433122, -0.3542168 ,
       -0.26351444,  0.16371189, -0.2343567 , -0.14021074, -0.51065423,
        0.91822819, -0.016925  ,  0.82121898, -0.66141671,  0.64997448,
       -0.34043588, -0.49353931, -0.47178329, -0.77910834,  0.03818044,
       -0.90527556,  0.22084984,  0.78548723,  0.96257658,  0.16163156,
        0.77209348, -0.4763343 ,  0.37139629,  0.67526542,  0.36307152,
       -0.53781242,  0.77988068, -0.49098905,  0.86581615, -0.81705616,
       -0.55282912, -0.50658996, -0.02371386,  0.61905264,  0.77912426,
        0.33477086,  0.45843727,  0.65743802,  0.42056622,  0.23197008,
       -0.1993805 , -0.58441169,  0.25241063, -0.55942379, -0.56961972,
        0.80372926,  0.4967549 , -0.10272114,  0.14978334, -0.23

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [10]:
def distance(P0,P1,p):
    t=P1 - P0
    l=(t**2).sum(axis=1)
    u=-((P0[:,0]-p[...,0])*t[:,0] + (P0[:,1]-p[...,1])*t[:,1]) / l
    u=u.reshape(len(u),1)
    d=P0+u*t-p
    return np.sqrt((d**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,( 1,2))
distance(P0, P1, p)

array([ 6.9310869 ,  1.67965454,  1.371434  ,  7.02261224,  9.6118269 ,
       10.68300407,  0.83696737,  7.39148569,  4.33644348,  3.10453269])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [12]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.28627034  5.84222588  4.39016062  2.97371071  1.18665123  6.94053254
   6.04737525  2.40321584  3.18433958  2.84268717]
 [ 0.48913312 12.62157873  2.89086343 10.16612996  6.14563496  3.39869214
   2.05837581  4.69401299  2.66617087  7.51479385]
 [ 5.02198661  2.7474516   3.86148466  0.59090075  5.15609887 10.01721043
   7.03541104  5.84161248  5.4845234   0.69466264]
 [ 2.92772028  4.4247254   9.48943532  2.57948132  0.26490788  1.92197435
  10.16745474  3.10403742  5.86956815  7.40677601]
 [ 1.62289026 11.85543161  1.57494381  9.00890409  4.55508903  5.58641397
   1.48930338  3.64887879  2.4587345   5.2670427 ]
 [11.31646218  6.87474984 15.04781286  6.5931913   5.5140351   6.69891497
  12.91438094  0.45910255  5.6186897  16.15808379]
 [13.22344675  5.14080445 17.59266126  5.25473628  4.74733901  8.39398207
  15.41868528  1.00245901  7.77531374 17.46554658]
 [ 4.8267951   2.17745389  4.34149722  1.11356015  5.59102656  9.88906148
   7.61383193  6.38041584  6.08454972  0.67767835]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [13]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 1 1 1 5 7 5 7 8 2]
 [4 1 8 1 3 4 3 1 0 7]
 [8 3 8 7 1 4 9 3 0 8]
 [3 6 6 4 0 1 1 8 2 9]
 [4 5 2 8 0 7 4 1 4 4]
 [7 1 4 2 0 5 8 9 6 2]
 [0 1 4 2 0 9 0 7 9 4]
 [3 7 3 2 0 9 3 6 4 3]
 [6 3 4 4 4 8 8 0 8 8]
 [7 3 6 8 6 6 8 0 9 9]]
[[0 0 0 0 0]
 [0 8 1 1 1]
 [0 4 1 8 1]
 [0 8 3 8 7]
 [0 3 6 6 4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [15]:
Z = np.arange(1,15,dtype=np.uint32)
A = stride_tricks.as_strided(Z,(11,4),(4,4))
print(A)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [16]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [17]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [18]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 4 1]
   [2 0 0]
   [0 2 0]]

  [[4 1 1]
   [0 0 4]
   [2 0 3]]

  [[1 1 3]
   [0 4 0]
   [0 3 4]]

  [[1 3 3]
   [4 0 1]
   [3 4 4]]

  [[3 3 1]
   [0 1 4]
   [4 4 3]]

  [[3 1 4]
   [1 4 4]
   [4 3 3]]

  [[1 4 0]
   [4 4 4]
   [3 3 4]]

  [[4 0 0]
   [4 4 4]
   [3 4 0]]]


 [[[2 0 0]
   [0 2 0]
   [4 0 0]]

  [[0 0 4]
   [2 0 3]
   [0 0 4]]

  [[0 4 0]
   [0 3 4]
   [0 4 2]]

  [[4 0 1]
   [3 4 4]
   [4 2 0]]

  [[0 1 4]
   [4 4 3]
   [2 0 0]]

  [[1 4 4]
   [4 3 3]
   [0 0 3]]

  [[4 4 4]
   [3 3 4]
   [0 3 1]]

  [[4 4 4]
   [3 4 0]
   [3 1 3]]]


 [[[0 2 0]
   [4 0 0]
   [1 3 4]]

  [[2 0 3]
   [0 0 4]
   [3 4 0]]

  [[0 3 4]
   [0 4 2]
   [4 0 0]]

  [[3 4 4]
   [4 2 0]
   [0 0 3]]

  [[4 4 3]
   [2 0 0]
   [0 3 4]]

  [[4 3 3]
   [0 0 3]
   [3 4 1]]

  [[3 3 4]
   [0 3 1]
   [4 1 2]]

  [[3 4 0]
   [3 1 3]
   [1 2 0]]]


 [[[4 0 0]
   [1 3 4]
   [0 0 4]]

  [[0 0 4]
   [3 4 0]
   [0 4 3]]

  [[0 4 2]
   [4 0 0]
   [4 3 1]]

  [[4 2 0]
   [0 0 3]
   [3 1 3]]

  [[2 0 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [19]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  9  7 17 13]
 [ 9  2  9 11  7]
 [ 7  9  7 42 12]
 [17 11 42  9  6]
 [13  7 12  6  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [20]:
p,n= 10, 20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
X=np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(X)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [23]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [24]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(10): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [26]:
Z = np.arange(250)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[245 246 247 248 249]
[247 248 245 246 249]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [27]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [30]:
Z=np.array([("HELLO",3.5,6),
            ("WORLD",4.6,5)])
R=np.core.records.fromarrays(Z.T,names='col1,col2,col3',formats='S8,f8,i8')
print(R)

[(b'HELLO', 3.5, 6) (b'WORLD', 4.6, 5)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [31]:
x=np.random.random(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.78 s per loop
10 loops, best of 5: 148 ms per loop
10 loops, best of 5: 125 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [32]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[..., np.newaxis, np.newaxis] == B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [33]:
Z = np.random.randint(0,5,(10,3))
print(Z)

[[0 3 1]
 [0 0 1]
 [1 0 4]
 [3 3 0]
 [1 3 4]
 [0 3 1]
 [4 0 4]
 [3 0 2]
 [0 0 0]
 [3 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [34]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [35]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [36]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.01690424, 0.1498562 , 0.04881569, 0.16519517, 0.11324525,
        0.00528412, 0.24641671, 0.03352007, 0.12855192, 0.04248411],
       [0.03809585, 0.33772001, 0.11001237, 0.37228835, 0.25521259,
        0.01190843, 0.55533142, 0.07554175, 0.28970811, 0.09574334],
       [0.04904449, 0.43477978, 0.14162961, 0.47928296, 0.32855996,
        0.01533088, 0.71493209, 0.09725223, 0.3729694 , 0.1232597 ],
       [0.0228091 , 0.20220287, 0.06586763, 0.22289995, 0.15280326,
        0.00712993, 0.3324932 , 0.04522906, 0.17345674, 0.05732434],
       [0.0155824 , 0.1381381 , 0.04499852, 0.15227764, 0.10438997,
        0.00487092, 0.227148  , 0.03089895, 0.11849972, 0.03916203],
       [0.02128918, 0.18872878, 0.06147844, 0.20804667, 0.14262098,
        0.00665481, 0.31033701, 0.04221515, 0.16189819, 0.05350445],
       [0.02950178, 0.26153349, 0.08519459, 0.28830353, 0.19763898,
        0.009222  , 0.43005377, 0.05850022, 0.22435263, 0.07414452],
       [0.02361347, 0.20933361, 0.0681904

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [38]:
Phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*Phi*np.cos(Phi)
y = a*Phi*np.sin(Phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
x,y

(array([  0.        ,   0.09950042,   0.19601332,   0.28660095,
          0.3684244 ,   0.43879128,   0.49520137,   0.53538953,
          0.55736537,   0.55944897,   0.54030231,   0.49895573,
          0.43482931,   0.34774848,   0.237954  ,   0.1061058 ,
         -0.04671924,  -0.21903564,  -0.40896377,  -0.61425018,
         -0.83229367,  -1.06017682,  -1.29470246,  -1.53243485,
         -1.76974492,  -2.00285904,  -2.22791076,  -2.44099478,
         -2.63822255,  -2.81577868,  -2.96997749,  -3.09731897,
         -3.19454328,  -3.25868324,  -3.28711385,  -3.27759841,
         -3.2283303 ,  -3.13797012,  -3.00567731,  -2.83113599,
         -2.61457448,  -2.35677818,  -2.05909545,  -1.72343644,
         -1.35226463,  -0.9485811 ,  -0.51590162,  -0.05822672,
          0.41999512,   0.91391061,   1.41831093,   1.92768649,
          2.43628669,   2.93818398,   3.42734153,   3.89768376,
          4.34316892,   4.75786287,   5.1360132 ,   5.47212274,
          5.76102172,   5.99793747,   6.

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [40]:
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n=4
M=np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M&=(X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [41]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.20193376  0.1824405 ]
